// Copyright 2025 lpiepiora
// SPDX-License-Identifier: GPL-2.0-or-later


#pragma once
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define SERIAL_PIO_USE_PIO0
#define SERIAL_USART_FULL_DUPLEX

#define EE_HANDS

#ifdef INIT_EE_HANDS_LEFT
#   define SERIAL_USART_TX_PIN GP15
#   define SERIAL_USART_RX_PIN GP14
#endif

#ifdef INIT_EE_HANDS_RIGHT
#   define SERIAL_USART_TX_PIN GP1
#   define SERIAL_USART_RX_PIN GP0
#endif

